name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install system dependencies
        run: sudo apt-get install clang-8 xvfb libqt5x11extras5-dev
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Download QM
        run: |
          wget https://github.com/QuantumLeaps/qm/releases/download/v5.1.3/qm_5.1.3-linux64.zip
          unzip qm_5.1.3-linux64.zip
          chmod u+x qm/bin/qm
          chmod u+x qm/bin/qm.sh
      - name: Run tests
        run: pytest --verbose
